In [1]:
import numpy as np
from FML.Regresion.prep import FL
from FML.Regresion.Linear import LR
from FML.Regresion.Ridge import RR
data_prep = FL('1.csv')
#data_prep.prep()
trainfile = 'train.csv'
testfile = 'test.csv'
validfile = 'validation.csv'
LR_train = LR(trainfile)
LR_train.formulate(11)
LR_train.cal_beta()
LR_train.test(testfile)

0.434576165535505

In [2]:
RR_train = RR(trainfile)
RR_train.formulate(11)
RR_train.normalize()
lamda = 0
RR_train.cal_beta(lamda)
RR_train.test(validfile)

matrix([[-26.65055938],
        [-26.4800576 ],
        [-26.63541002],
        [-26.17788006],
        [-26.68258888],
        [-26.73234567],
        [-26.65667557],
        [-27.21972838],
        [-27.01243066],
        [-27.55645822],
        [-27.16243226],
        [-26.88689754],
        [-26.91202025],
        [-26.13565301],
        [-27.40971239],
        [-27.00092752],
        [-26.64127649],
        [-26.18819063],
        [-27.55378162],
        [-26.07571379],
        [-26.78889855],
        [-26.66156446],
        [-27.0192654 ],
        [-26.72365939],
        [-26.50734829],
        [-27.12153331],
        [-26.61500328],
        [-26.72242967],
        [-26.47688051],
        [-27.10344233],
        [-26.32099074],
        [-25.91804486],
        [-26.28041793],
        [-27.32102253],
        [-27.77270952],
        [-26.7976784 ],
        [-27.15963079],
        [-27.28409335],
        [-26.46814307],
        [-26.7994471 ],
        [-28.21924876],
        [-27.230

In [3]:
lamda = 0
RR_train.cal_beta(lamda)
rec = RR_train.test(validfile)
for i in np.arange(-500,500,0.5):
    RR_train.cal_beta(i)
    temp = RR_train.test(validfile)
    if temp < rec:
        rec = temp
        lamda = i
RR_train.cal_beta(lamda)
RR_train.test(validfile)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
np.matrix([[1,1],[2,2]])-np.matrix([[0],[2]]).transpose()

In [4]:
3*np.identity(3)

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [3]:
RR_train.tX

matrix([[1.        , 0.59748428, 0.27819549, ..., 0.82044888, 0.29      ,
         0.74496644],
        [1.        , 0.37735849, 0.43609023, ..., 0.89276808, 0.335     ,
         0.83892617],
        [1.        , 0.46540881, 0.27067669, ..., 0.84538653, 0.34      ,
         0.73825503],
        ...,
        [1.        , 0.72327044, 0.33834586, ..., 0.81296758, 0.555     ,
         0.73825503],
        [1.        , 0.42767296, 0.5112782 , ..., 0.85037406, 0.26      ,
         0.74496644],
        [1.        , 0.32075472, 0.31578947, ..., 0.91770574, 0.365     ,
         0.91275168]])